#!/usr/bin/env bash

# Workers
WORKERS=(
    node_1
    node_2
    node_3
)

MASTERS=(
    node_0
    node_1
    node_2
)
# Variables
KEY_CN="Kubernetes"
KEY_COUNTRY="Mars"
KEY_LOCATION="Acidalia Planitia"
KEY_ORG="Kubernetes"
KEY_OU="R&D"
KEY_ST="N/A"

KEY_SIZE=4096

admin_generation() {

    cat > admin-csr.json <<EOF
{
  "CN": "admin",
  "key": {
    "algo": "rsa",
    "size": $KEY_SIZE
  },
  "names": [
    {
      "C": "$KEY_COUNTRY",
      "L": "$KEY_LOCATION",
      "O": "system:masters",
      "OU": "$KEY_OU",
      "ST": "$KEY_ST"
    }
  ]
}
EOF

    cfssl gencert \
          -ca=ca.pem \
          -ca-key=ca-key.pem \
          -config=ca-config.json \
          -profile=kubernetes \
          admin-csr.json | cfssljson -bare admin
}

main() {
       admin_generation
}

main
